"""create threat table

Revision ID: 1a93fa0172f2
Revises: 08b77bf75df7
Create Date: 2026-06-29 13:49:29.621910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a93fa0172f2'
down_revision = '08b77bf75df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threats')
    # ### end Alembic commands ###
