"""add_abuseipdb_enrichment_table

Revision ID: a3bbfe9e6e98
Revises: 1435203c7952
Create Date: 2026-07-01 13:01:09.306518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bbfe9e6e98'
down_revision = '1435203c7952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuseipdb_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('abuse_confidence_score', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('isp', sa.String(length=256), nullable=True),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('usage_type', sa.String(length=100), nullable=True),
    sa.Column('total_reports', sa.Integer(), nullable=True),
    sa.Column('last_reported_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abuseipdb_enrichments')
    # ### end Alembic commands ###
